from oc_platform import settings
from django.core.management import setup_environ
setup_environ(settings)

cluster_groups = [['Make sense of problems and persevere in solving them.',
'Reason abstractly and quantitatively.',
'Construct viable arguments and critique the reasoning of others.',
'Model with mathematics.',
'Use appropriate tools strategically.',
'Attend to precision.',
'Look for and make use of structure.',
'Look for and express regularity in repeated reasoning.'],

['Know number names and the count sequence.',
'Count to tell the number of objects.',
'Compare numbers.',
'Understand addition, and understand subtraction.',
'Work with numbers 11-19 to gain foundations for place value.',
'Describe and compare measurable attributes.',
'Classify objects and count the number of objects in each category.',
'Identify and describe shapes.',
'Analyze, compare, create, and compose shapes.'],

['Represent and solve problems involving addition and subtraction.',
'Understand and apply properties of operations and the relationship between addition and subtraction.',
'Add and subtract within 20.',
'Work with addition and subtraction equations.',
'Extend the counting sequence.',
'Understand place value.',
'Use place value understanding and properties of operations to add and subtract.',
'Measure lengths indirectly and by iterating length units.',
'Tell and write time.',
'Represent and interpret data.',
'Reason with shapes and their attributes.'],

['Represent and solve problems involving addition and subtraction.',
'Add and subtract within 20.',
'Work with equal groups of objects to gain foundations for multiplication.',
'Understand place value.',
'Use place value understanding and properties of operations to add and subtract.',
'Measure and estimate lengths in standard units.',
'Relate addition and subtraction to length.',
'Work with time and money.',
'Represent and interpret data.',
'Reason with shapes and their attributes.'],

['Represent and solve problems involving multiplication and division.',
'Understand properties of multiplication and the relationship between multiplication and division.',
'Multiply and divide within 100.',
'Solve problems involving the four operations, and identify and explain patterns in arithmetic.',
'Use place value understanding and properties of operations to perform multi-digit arithmetic.',
'Develop understanding of fractions as numbers.',
'Solve problems involving measurement and estimation.',
'Represent and interpret data.',
'Geometric measurement: understand concepts of area and relate area to multiplication and to addition.',
'Geometric measurement: recognize perimeter.',
'Reason with shapes and their attributes.'],

['Use the four operations with whole numbers to solve problems.',
'Gain familiarity with factors and multiples.',
'Generate and analyze patterns.',
'Generalize place value understanding for multi-digit whole numbers.',
'Use place value understanding and properties of operations to perform multi-digit arithmetic.',
'Extend understanding of fraction equivalence and ordering.',
'Build fractions from unit fractions.',
'Understand decimal notation for fractions, and compare decimal fractions.',
'Solve problems involving measurement and conversion of measurements.',
'Represent and interpret data.',
'Geometric measurement: understand concepts of angle and measure angles.',
'Draw and identify lines and angles, and classify shapes by properties of their lines and angles.'],

['Write and interpret numerical expressions.',
'Analyze patterns and relationships.',
'Understand the place value system.',
'Perform operations with multi-digit whole numbers and with decimals to hundredths.',
'Use equivalent fractions as a strategy to add and subtract fractions.',
'Apply and extend previous understandings of multiplication and division.',
'Convert like measurement units within a given measurement system.',
'Represent and interpret data.',
'Geometric measurement: understand concepts of volume.',
'Graph points on the coordinate plane to solve real-world and mathematical problems.',
'Classify two-dimensional figures into categories based on their properties.'],

['Understand ratio concepts and use ratio reasoning to solve problems.',
'Apply and extend previous understandings of multiplication and division to divide fractions by fractions.',
'Compute fluently with multi-digit numbers and find common factors and multiples.',
'Apply and extend previous understandings of numbers to the system of rational numbers.',
'Apply and extend previous understandings of arithmetic to algebraic expressions.',
'Reason about and solve one-variable equations and inequalities.',
'Represent and analyze quantitative relationships between dependent and independent variables.',
'Solve real-world and mathematical problems involving area, surface area, and volume.',
'Develop understanding of statistical variability.',
'Summarize and describe distributions.'],

['Analyze proportional relationships and use them to solve real-world and mathematical problems.',
'Apply and extend previous understandings of operations with fractions.',
'Use properties of operations to generate equivalent expressions.',
'Solve real-life and mathematical problems using numerical and algebraic expressions and equations.',
'Draw construct, and describe geometrical figures and describe the relationships between them.',
'Solve real-life and mathematical problems involving angle measure, area, surface area, and volume.',
'Use random sampling to draw inferences about a population.',
'Draw informal comparative inferences about two populations.',
'Investigate chance processes and develop, use, and evaluate probability models.'],

['Know that there are numbers that are not rational, and approximate them by rational numbers.',
'Expressions and Equations Work with radicals and integer exponents.',
'Understand the connections between proportional relationships, lines, and linear equations.',
'Analyze and solve linear equations and pairs of simultaneous linear equations.',
'Define, evaluate, and compare functions.',
'Use functions to model relationships between quantities.',
'Understand congruence and similarity using physical models, transparencies, or geometry software.',
'Understand and apply the Pythagorean Theorem.',
'Solve real-world and mathematical problems involving volume of cylinders, cones, and spheres.',
'Investigate patterns of association in bivariate data.'],

['Extend the properties of exponents to rational exponents.',
'Use properties of rational and irrational numbers.',
'Reason quantitatively and use units to solve problems.',
'Perform arithmetic operations with complex numbers.',
'Represent complex numbers and their operations on the complex plane.',
'Use complex numbers in polynomial identities and equations.',
'Represent and model with vector quantities.',
'Perform operations on vectors.',
'Perform operations on matrices and use matrices in applications.'],

['Interpret the structure of expressions.',
'Write expressions in equivalent forms to solve problems.',
'Perform arithmetic operations on polynomials.',
'Understand the relationship between zeros and factors of polynomials.',
'Use polynomial identities to solve problems.',
'Rewrite rational expressions.',
'Create equations that describe numbers or relationships.',
'Understand solving equations as a process of reasoning and explain the reasoning.',
'Solve equations and inequalities in one variable.',
'Solve systems of equations.',
'Represent and solve equations and inequalities graphically.'],

['Understand the concept of a function and use function notation.',
'Interpret functions that arise in applications in terms of the context.',
'Analyze functions using different representations.',
'Build a function that models a relationship between two quantities.',
'Build new functions from existing functions.',
'Construct and compare linear, quadratic, and exponential models and solve problems.',
'Interpret expressions for functions in terms of the situation they model.',
'Extend the domain of trigonometric functions using the unit circle.',
'Model periodic phenomena with trigonometric functions.',
'Prove and apply trigonometric identities.'],

['Experiment with transformations in the plane',
'Understand congruence in terms of rigid motions',
'Prove geometric theorems',
'Make geometric constructions',
'Understand similarity in terms of similarity transformations',
'Prove theorems involving similarity',
'Define trigonometric ratios and solve problems involving right triangles',
'Apply trigonometry to general triangles',
'Understand and apply theorems about circles',
'Find arc lengths and areas of sectors of circles',
'Translate between the geometric description and the equation for a conic section',
'Use coordinates to prove simple geometric theorems algebraically',
'Explain volume formulas and use them to solve problems',
'Visualize relationships between two-dimensional and three-dimensional objects',
'Apply geometric concepts in modeling situations'],

['Summarize, represent, and interpret data on a single count or measurement variable',
'Summarize, represent, and interpret data on two categorical and quantitative variables',
'Interpret linear models',
'Understand and evaluate random processes underlying statistical experiments',
'Make inferences and justify conclusions from sample surveys, experiments, and observational studies',
'Understand independence and conditional probability and use them to interpret data',
'Use the rules of probability to compute probabilities of compound events.',
'Calculate expected values and use them to solve problems',
'Use probability to evaluate outcomes of decisions']]

from meta.models import Category
from django.template.defaultfilters import slugify

parent = Category.objects.get(pk=26)

for cluster_group in cluster_groups:
    for (position, cluster) in enumerate(cluster_group):
        category = Category(
            title=cluster,
            position=position,
            parent=parent,
            slug=slugify(cluster)
        )
        category.save()